Added php7.1 support
PGSSoft/php-docker-skeleton pull request #14
Opened 2017-04-06 09:10 UTC by janhryniukpgs

@tarnawski @partikus @dominikpgs CR please.

2017-04-06 09:23 UTC, partikus commented
@janhryniukpgs good job, could you switch default php version to `7.1`? so by default `./docker.sh run` will running php7.1 version instead of 7.0

2017-04-06 09:23 UTC, partikus commented
@janhryniukpgs don't forget to update [.travis.yml](https://github.com/PGSSoft/php-docker-skeleton/blob/master/.travis.yml)

2017-04-06 09:25 UTC, partikus requested changes
- [ ] `7.1` as a default version 
- [ ] missing update of `.travis.yml` file

2017-04-06 09:25 UTC, partikus commented on docker.sh
> +    echo -e "'run-7.1' - is running dev env and attaching tty";
`7.1` should be run as default one

2017-04-10 14:05 UTC, dominikpgs requested changes
@janhryniukpgs consider edit README and add 7.1 note https://github.com/PGSSoft/php-docker-skeleton/blob/master/README.md

2017-04-10 14:23 UTC, dominikpgs commented
@janhryniukpgs 👍

2017-04-10 15:55 UTC, partikus requested changes
```
env:
  - PROJECT_COMMAND=build-71
  - PROJECT_COMMAND=build-71-coverage
  - PROJECT_COMMAND=build-7
  - PROJECT_COMMAND=build-7-coverage
  - PROJECT_COMMAND=build-56
  - PROJECT_COMMAND=build-56-coverage
```
and we could set `build` task as an alias for `build-71`

2017-04-10 15:55 UTC, partikus commented on .travis.yml
> +  - PPROJET_COMMAND=build-7
typo: `PPROJET_COMMAND` => `PROJECT_COMMAND`

2017-04-11 09:03 UTC, jhryniuk commented
@partikus @dominikpgs ping

2017-04-11 09:16 UTC, partikus commented on docker.sh
> +    'run-coverage-7')
duplicated with [149](https://github.com/PGSSoft/php-docker-skeleton/pull/14/files#diff-51df7a7eb9518d36a5475c9cff55f3cbR149) line

2017-04-11 09:17 UTC, partikus commented on docker.sh
> +    'run-coverage-7')
rename `run-7-coverage`, imho `coverage` should be a suffix for builds with `xdebug`

2017-04-11 10:20 UTC, jhryniuk commented on docker.sh
> +    'run-coverage-7')
fixed

2017-04-11 12:23 UTC, partikus commented
@janhryniukpgs Could you update `README.md` badges icons, please? Then I will merge it

2017-04-11 12:23 UTC, partikus approved these changes

2017-04-11 13:57 UTC, merged