[WIP] Added Jenkinsfile
PGSSoft/php-docker-skeleton pull request #17
Opened 2017-04-12 11:44 UTC by jhryniuk

2017-04-12 11:51 UTC, partikus requested changes

2017-04-12 11:51 UTC, partikus commented on Jenkinsfile
> +    agent ant
why `ant`?

2017-04-12 11:51 UTC, partikus commented on Jenkinsfile
> +        git url: 'https://github.com/PGSSoft/php-docker-skeleton'
better is to use [checkout](https://jenkins.io/doc/pipeline/steps/workflow-scm-step/#checkout-general-scm)

2017-04-12 11:51 UTC, partikus commented on Jenkinsfile
> +        failFast: true|false
`failFast: true|false` what exactly this line is doing?

2017-04-12 11:51 UTC, partikus commented on Jenkinsfile
> +    stage('Code Coverage') {
IMHO does not make sense running tests twice (once without coverage and second one with coverage)

2017-04-12 11:51 UTC, partikus commented on Jenkinsfile
> +        sh './docker.sh build-images';
building images could be run parallel

2017-04-12 11:52 UTC, partikus commented
@jhryniuk could you read my comments (unfortunately marked as `outdated`)?

2017-04-13 10:29 UTC, jhryniuk commented
@partikus @dominikpgs CR please

2017-05-01 10:10 UTC, partikus commented
@jhryniuk are you going to continue this PR ?

2017-05-01 20:11 UTC, jhryniuk commented
I don't have idea how to solve this.

2017-07-15 22:16 UTC, partikus commented
Closed in favor of #28

2017-07-15 22:16 UTC, closed without merging